_wandb:
    value:
        cli_version: 0.21.4
        e:
            vnjd9qp0ieelh8aewwki0cibm986lc63:
                args:
                    - -d
                    - /scratch/s223540177/Time-Series-Library/data/all_datasets/ETT-small/ETTh1.csv
                    - -p
                    - "96"
                    - -m
                    - /scratch/s223540177/Time-MoE/checkpoints/50M_etth1
                    - --data
                    - ETTh1
                    - --seq_len
                    - "2048"
                    - --batch_size
                    - "512"
                codePath: run_eval.py
                codePathLocal: run_eval.py
                cpu_count: 72
                cpu_count_logical: 72
                cudaVersion: "12.7"
                disk:
                    /:
                        total: "470822744064"
                        used: "192030244864"
                email: Davido111200@gmail.com
                executable: /scratch/s223540177/.conda/envs/timemoe/bin/python
                git:
                    commit: 1dfb7a3a62c79895832bf13a9e368110d26e6a7e
                    remote: git@github.com:Davido111200/Time-MoE.git
                gpu: NVIDIA H100 80GB HBM3
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-855922e6-65b5-2c85-68a4-28109ff52005
                host: h100-m-03
                memory:
                    total: "1081678008320"
                os: Linux-5.15.0-161-generic-x86_64-with-glibc2.35
                program: /home/s223540177/Time-MoE/run_eval.py
                python: CPython 3.10.18
                root: /home/s223540177/Time-MoE
                slurm:
                    job_id: "47656"
                startedAt: "2025-12-14T15:56:56.682150Z"
                writerId: vnjd9qp0ieelh8aewwki0cibm986lc63
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 5
                - 11
                - 15
                - 49
                - 53
            "2":
                - 1
                - 5
                - 11
                - 15
                - 49
                - 53
                - 71
            "4": 3.10.18
            "5": 0.21.4
            "6": 4.40.1
            "8":
                - 2
            "12": 0.21.4
            "13": linux-x86_64
